Example to print IMU data
mavlink/MAVSDK-Python pull request #727
Opened 2024-09-03 05:54 UTC by dr0ne-guy

I have created a python file that prints the IMU data from the FC

2024-09-03 07:37 UTC, JonasVautherin requested changes

2024-09-03 07:37 UTC, JonasVautherin commented on examples/highres_imu.py
> +        await asyncio.sleep(0)  # Sleep for a second between each print
This is not sleeping for a second, and in any case you should not sleep here :see_no_evil:

2024-09-03 08:49 UTC, dr0ne-guy commented
@JonasVautherin I have changed the sleep timer.

2024-09-03 11:39 UTC, JonasVautherin commented
But you should not sleep there :see_no_evil:. You should consume the events as they arrive. Sleeping may just slow them down and accumulate a delay that you don't want :innocent:.

2024-09-03 12:26 UTC, dr0ne-guy commented
I have removed the delay 😅

2024-09-03 19:59 UTC, julianoes approved these changes
Thanks for that!

2024-09-03 22:04 UTC, julianoes commented
If you can fix the style issue then this is good to go in, thanks.
https://github.com/mavlink/MAVSDK-Python/actions/runs/10682857899/job/29632558957?pr=727

2024-09-04 05:02 UTC, dr0ne-guy commented
I have changed the style

2024-09-04 07:16 UTC, merged